// autogenerated file from bo4.json, do not edit this file
#pragma once
#include <span>
#include <hook/refs.hpp>
#include <hook/scan_container.hpp>

namespace bo4 {
    constexpr const char* GAME_ID = "bo4";

    // dumped module name
    constexpr const char* MODULE_NAME = "BlackOps4_dump.exe";
    // first asset name
    constexpr const char* FIRST_ASSET_NAME = "physpreset";
    // end asset name
    constexpr const char* END_ASSET_NAME = "assetlist";

    // defined c declarations
    struct XAsset;
    struct XBlock;
    struct XHash;
    struct XAssetEntryPoolEntry;

    // common fastfiles names
    std::span<const char*> GetCommonFastFiles();

    /*
     * Fast Files functions
     */
    
    // Allocate XFile loading pointer
    extern hook::refs::Ref<void* (int alignment)> DB_AllocStreamPos;
    // Alloc the XBlock buffers
    extern hook::refs::Ref<void (size_t *blockSize, const char *filename, const char *filename2, XBlock *blocks, int side, int *loaded)> DB_AllocXBlocks;
    // Convert XFile offset to alias
    extern hook::refs::Ref<void (void** data)> DB_ConvertOffsetToAlias;
    // Convert XFile offset to pointer
    extern hook::refs::Ref<void (void** data)> DB_ConvertOffsetToPointer;
    // Find a XAsset header
    extern hook::refs::Ref<void> DB_FindXAssetHeader;
    // Get XFile offset data
    extern hook::refs::Ref<void* (uint64_t ref)> DB_GetOffsetData;
    // Move XFile loading stream
    extern hook::refs::Ref<void (size_t size)> DB_IncStreamPos;
    // Init the XFile streams with XBlock buffers
    extern hook::refs::Ref<void (XBlock *blocks)> DB_InitStreams;
    // Insert file to loading stream
    extern hook::refs::Ref<const void** ()> DB_InsertPointer;
    // Link an XAsset entry
    extern hook::refs::Ref<XAssetEntryPoolEntry* (XAsset *newEntry, bool allowOverride)> DB_LinkXAssetEntry;
    // Load data from XFile
    extern hook::refs::Ref<void (byte *pos, int size)> DB_LoadXFileData;
    // Pop XFile loading stream block
    extern hook::refs::Ref<void ()> DB_PopStreamPos;
    // Push XFile loading stream block
    extern hook::refs::Ref<void (int index)> DB_PushStreamPos;
    // Load a stream of the loaded XFile
    extern hook::refs::Ref<bool (bool atStreamStart, void *ptr, size_t size)> Load_Stream;
    // Load an XAsset of the loaded XFile
    extern hook::refs::Ref<void (bool atStreamStart, XAsset *asset)> Load_XAsset;
    // Load an XHash
    extern hook::refs::Ref<void (XHash* hash)> Load_XHash;
    // Load an XString
    extern hook::refs::Ref<void (const char** str)> Load_XStringCustom;

    /*
     * Load the scans for the game
     * @param scan game
     */
    void LoadScans(hook::scan_container::ScanContainer& scan);
} // namespace bo4
