// autogenerated file from bo4.json, do not edit this file
#include <includes_shared.hpp>
#include "bo4_generated.hpp"

namespace bo4 {
    namespace {
        enum ScanType {
            ST_RELATIVE,
            ST_ABSOLUTE,
            ST_OFFSET,
        };

        struct ScanInformation {
            const char* id;
            const char* scan;
            ScanType type;
            int offset;
            int postOffset;
            bool single;
            void** ref;
        };
    }

    // common fastfiles names
    std::span<const char*> GetCommonFastFiles() {
        static const char* files[] { 
            "zone/core_common.ff",
            "zone/mp_common.ff",
            "zone/mp_common_all.ff",
            "zone/mp_common_script.ff",
            "zone/wz_common.ff",
            "zone/wz_common_all.ff",
            "zone/wz_common_script.ff",
            "zone/zm_common.ff",
            "zone/zm_common_all.ff",
            "zone/zm_common_script.ff",
        };
        return files;
    }

    // refs
    
    // DB_AllocStreamPos
    hook::refs::Ref<void* (int alignment)> DB_AllocStreamPos{ nullptr };
    // DB_AllocXBlocks
    hook::refs::Ref<void (size_t *blockSize, const char *filename, const char *filename2, XBlock *blocks, int side, int *loaded)> DB_AllocXBlocks{ nullptr };
    // DB_ConvertOffsetToAlias
    hook::refs::Ref<void (void** data)> DB_ConvertOffsetToAlias{ nullptr };
    // DB_ConvertOffsetToPointer
    hook::refs::Ref<void (void** data)> DB_ConvertOffsetToPointer{ nullptr };
    // DB_FindXAssetHeader
    hook::refs::Ref<void> DB_FindXAssetHeader{ nullptr };
    // DB_GetOffsetData
    hook::refs::Ref<void* (uint64_t ref)> DB_GetOffsetData{ nullptr };
    // DB_IncStreamPos
    hook::refs::Ref<void (size_t size)> DB_IncStreamPos{ nullptr };
    // DB_InitStreams
    hook::refs::Ref<void (XBlock *blocks)> DB_InitStreams{ nullptr };
    // DB_InsertPointer
    hook::refs::Ref<const void** ()> DB_InsertPointer{ nullptr };
    // DB_LinkXAssetEntry
    hook::refs::Ref<XAssetEntryPoolEntry* (XAsset *newEntry, bool allowOverride)> DB_LinkXAssetEntry{ nullptr };
    // DB_LoadXFileData
    hook::refs::Ref<void (byte *pos, int size)> DB_LoadXFileData{ nullptr };
    // DB_PopStreamPos
    hook::refs::Ref<void ()> DB_PopStreamPos{ nullptr };
    // DB_PushStreamPos
    hook::refs::Ref<void (int index)> DB_PushStreamPos{ nullptr };
    // Load_Stream
    hook::refs::Ref<bool (bool atStreamStart, void *ptr, size_t size)> Load_Stream{ nullptr };
    // Load_XAsset
    hook::refs::Ref<void (bool atStreamStart, XAsset *asset)> Load_XAsset{ nullptr };
    // Load_XHash
    hook::refs::Ref<void (XHash* hash)> Load_XHash{ nullptr };
    // Load_XStringCustom
    hook::refs::Ref<void (const char** str)> Load_XStringCustom{ nullptr };

    static ScanInformation scans[] { 
        {
            .id = "fastfile.DB_AllocStreamPos",
            .scan = "E8 ?? ?? ?? ?? 48 89 47 18 48 8B CF",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_AllocStreamPos.ptr
        },
        {
            .id = "fastfile.DB_AllocXBlocks",
            .scan = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 54 41 55 41 56 41 57 48 83 EC 50 4C 8B",
            .type = ST_ABSOLUTE,
            .offset = 0,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_AllocXBlocks.ptr
        },
        {
            .id = "fastfile.DB_ConvertOffsetToAlias",
            .scan = "4C 8B 01 49 FF C8 49 8B C0 48 C1 E8 3C 48 8D 14 40 48 B8 FF FF FF FF FF FF FF 0F 4C 23 C0 48 8B 05 ?? ?? ?? ?? 48",
            .type = ST_ABSOLUTE,
            .offset = 0,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_ConvertOffsetToAlias.ptr
        },
        {
            .id = "fastfile.DB_ConvertOffsetToPointer",
            .scan = "E8 ?? ?? ?? ?? 48 8D 4B 18 E8 ?? ?? ?? ?? 45 33 F6 48 8D 7B 38 33 C9",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_ConvertOffsetToPointer.ptr
        },
        {
            .id = "fastfile.DB_FindXAssetHeader",
            .scan = "E8 ?? ?? ?? ?? 48 85 C0 75 1B 48 8B CB E8",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_FindXAssetHeader.ptr
        },
        {
            .id = "fastfile.DB_GetOffsetData",
            .scan = "E8 ?? ?? ?? ?? 48 89 44 24 28 0F 10 44 24 20 0F 11 46 20 33 C9",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_GetOffsetData.ptr
        },
        {
            .id = "fastfile.DB_IncStreamPos",
            .scan = "E8 ?? ?? ?? ?? 0F B6 C3 48 83 C4 20 5B C3 B0 01",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_IncStreamPos.ptr
        },
        {
            .id = "fastfile.DB_InitStreams",
            .scan = "33 D2 48 89 0D ?? ?? ?? ?? 48",
            .type = ST_ABSOLUTE,
            .offset = 0,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_InitStreams.ptr
        },
        {
            .id = "fastfile.DB_InsertPointer",
            .scan = "48 89 5C 24 08 48 63 15",
            .type = ST_ABSOLUTE,
            .offset = 0,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_InsertPointer.ptr
        },
        {
            .id = "fastfile.DB_LinkXAssetEntry",
            .scan = "E8 ?? ?? ?? ?? 48 8B 50 08 48 89 13",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_LinkXAssetEntry.ptr
        },
        {
            .id = "fastfile.DB_LoadXFileData",
            .scan = "85 D2 0F 8E 56 01 00 00 41 54 41 56 48 83 EC 38 48 89 5C 24",
            .type = ST_ABSOLUTE,
            .offset = 0,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_LoadXFileData.ptr
        },
        {
            .id = "fastfile.DB_PopStreamPos",
            .scan = "E8 ?? ?? ?? ?? 8B 05 ?? ?? ?? ?? FF C8 89 05 ?? ?? ?? ?? F6 05",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_PopStreamPos.ptr
        },
        {
            .id = "fastfile.DB_PushStreamPos",
            .scan = "E8 ?? ?? ?? ?? 48 8B 7C 24 60 48 8B D7 33 C9 E8 ?? ?? ?? ?? E8",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&DB_PushStreamPos.ptr
        },
        {
            .id = "fastfile.Load_Stream",
            .scan = "E8 ?? ?? ?? ?? 8B FE 45 85 FF 7E 22",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&Load_Stream.ptr
        },
        {
            .id = "fastfile.Load_XAsset",
            .scan = "E8 ?? ?? ?? ?? 48 83 C3 10 80 3D ?? ?? ?? ?? ?? 75 07",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&Load_XAsset.ptr
        },
        {
            .id = "fastfile.Load_XHash",
            .scan = "E8 ?? ?? ?? ?? 48 8B CE E8 ?? ?? ?? ?? 48 83 7E 10 00 74 1F B9 1F 00 00 00",
            .type = ST_RELATIVE,
            .offset = 9,
            .postOffset = 0,
            .single = false,
            .ref = (void**)&Load_XHash.ptr
        },
        {
            .id = "fastfile.Load_XStringCustom",
            .scan = "E8 ?? ?? ?? ?? EB 09 48 8D 4F 48 E8 ?? ?? ?? ?? 33 C9",
            .type = ST_RELATIVE,
            .offset = 1,
            .postOffset = 0,
            .single = true,
            .ref = (void**)&Load_XStringCustom.ptr
        },
    };

    void LoadScans(hook::scan_container::ScanContainer& scan) {
        bool oldIgnoreMissing{ scan.ignoreMissing };
        scan.ignoreMissing = true;
        for (ScanInformation& info : scans) {
            switch (info.type) {
            case ST_RELATIVE:
                if (info.single) {
                    *info.ref = scan.ScanSingle(info.scan, info.id).GetRelative<int32_t, byte*>(info.offset, info.postOffset);
                } else {
                    *info.ref = scan.ScanAny(info.scan, info.id).GetRelative<int32_t, byte*>(info.offset, info.postOffset);
                }
                break;
            case ST_ABSOLUTE:
                if (info.single) {
                    *info.ref = scan.ScanSingle(info.scan, info.id).GetPtr<byte*>(info.offset) + info.postOffset;
                } else {
                    *info.ref = scan.ScanAny(info.scan, info.id).GetPtr<byte*>(info.offset) + info.postOffset;            
                }
                break;
            case ST_OFFSET:
                if (info.scan[0] == '0' && info.scan[1] == 'x') {
                    *info.ref = hook::process::Relativise(std::strtoull(&info.scan[2], nullptr, 16));
                } else {
                    *info.ref = hook::process::Relativise(std::strtoull(info.scan, nullptr, 10));
                }
                break;
            }
        }
        scan.ignoreMissing = oldIgnoreMissing;
        if (scan.foundMissing && !oldIgnoreMissing) {
            throw std::runtime_error("Missing scans found");
        }
    }

} // namespace bo4
